name: Build and deploy

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm install
        
      - name: Build app
        run: npm run build

      # - uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: 1.0.15

      # - name: Install dependencies
      #   run: bun install
        
      # - name: Build app
      #   run: bun run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy files to website bucket
        run: |
          cd build
          aws s3 sync . s3://daoust-guitar-teacher
